//
//  CategoryModelTests.swift
//  ColourNoteXCTests
//
//  Unit tests for the Category model class and UIColor hex extension.
//

import Testing
import UIKit
@testable import ColourNote

struct CategoryModelTests {

    @Test func categoryHasAutoGeneratedUUID() {
        let cat = ColourNote.Category()
        #expect(!cat.uuid.isEmpty)
    }

    @Test func categoryDefaultsAreCorrect() {
        let cat = ColourNote.Category()
        #expect(cat.categoryId == 0)
        #expect(cat.colorHex == "#FFFFFF")
        #expect(cat.sortOrder == 0)
        #expect(cat.isProtected == false)
    }

    @Test func categoryModifiedAtIsSetOnInit() {
        let before = Int(Date().timeIntervalSince1970 * 1000) - 1000
        let cat = ColourNote.Category()
        let after = Int(Date().timeIntervalSince1970 * 1000) + 1000
        #expect(cat.modifiedAt != nil)
        if let ts = cat.modifiedAt {
            #expect(ts > before && ts < after)
        }
    }

    @Test func getDefaultCategoriesReturns5() {
        let cats = ColourNote.Category.getDefaultCategories()
        #expect(cats.count == 5)
    }

    @Test func getDefaultCategoriesHaveUniqueIds() {
        let cats = ColourNote.Category.getDefaultCategories()
        let ids = cats.map { $0.categoryId }
        #expect(Set(ids).count == ids.count)
    }

    @Test func getDefaultCategoriesHaveUniqueNames() {
        let cats = ColourNote.Category.getDefaultCategories()
        let names = cats.map { $0.categoryName }
        #expect(Set(names).count == names.count)
    }

    @Test func getColorReturnsValidUIColor() {
        let cat = ColourNote.Category(categoryId: 1, categoryName: "Test", colorHex: "#FF0000", sortOrder: 1)
        let color = cat.getColor()
        // Red component should be 1.0, not the fallback white
        var r: CGFloat = 0
        color.getRed(&r, green: nil, blue: nil, alpha: nil)
        #expect(r > 0.9)
    }

    @Test func getColorFallsBackToWhiteForInvalidHex() {
        let cat = ColourNote.Category(categoryId: 1, categoryName: "Test", colorHex: "INVALID", sortOrder: 1)
        let color = cat.getColor()
        // UIColor(hexString:) returns nil for invalid input; getColor() falls back to .white
        #expect(color == .white)
    }

    @Test func uiColorInitFromValidHex() {
        let color = UIColor(hexString: "#1A2B3C")
        #expect(color != nil)
    }

    @Test func uiColorInitFromInvalidHexReturnsNil() {
        let color = UIColor(hexString: "GGGGGG")
        #expect(color == nil)
    }

    @Test func uiColorInitFromShortHexReturnsNil() {
        let color = UIColor(hexString: "#FFF")
        #expect(color == nil)
    }

    @Test func uiColorRoundTrip() {
        let hex = "#1A2B3C"
        let color = UIColor(hexString: hex)!
        let result = color.toHexString().lowercased()
        #expect(result == hex.lowercased())
    }
}
