//
//  NoteModelTests.swift
//  ColourNoteXCTests
//
//  Unit tests for the Note model class.
//

import Testing
@testable import ColourNote

struct NoteModelTests {

    @Test func noteHasAutoGeneratedUUID() {
        let note = Note()
        #expect(!note.uuid.isEmpty)
    }

    @Test func noteUUIDIsUniquePerInstance() {
        let a = Note()
        let b = Note()
        #expect(a.uuid != b.uuid)
    }

    @Test func noteInitWithExplicitUUID() {
        let id = "explicit-uuid-1234"
        let note = Note(noteId: 1, uuid: id, noteName: "X", editedTime: 0, noteText: "")
        #expect(note.uuid == id)
    }

    @Test func noteInitWithNilUUIDGeneratesOne() {
        let note = Note(noteId: 1, uuid: nil, noteName: "X", editedTime: 0, noteText: "")
        #expect(!note.uuid.isEmpty)
    }

    @Test func noteDefaultsToNotDeleted() {
        let note = Note()
        #expect(note.isDeleted == false)
        #expect(note.deletedDate == nil)
    }

    @Test func noteDefaultContentFormatIsMarkdown() {
        let note = Note()
        #expect(note.contentFormat == "markdown")
    }

    @Test func noteInitPreservesAllFields() {
        let note = Note(
            noteId: 7,
            uuid: "uuid-seven",
            noteName: "Shopping list",
            editedTime: 1_700_000_000_000,
            noteText: "Milk, eggs",
            categoryId: 3,
            isDeleted: true,
            deletedDate: 1_700_000_001_000,
            contentFormat: "markdown"
        )
        #expect(note.noteId == 7)
        #expect(note.uuid == "uuid-seven")
        #expect(note.noteName == "Shopping list")
        #expect(note.editedTime == 1_700_000_000_000)
        #expect(note.noteText == "Milk, eggs")
        #expect(note.categoryId == 3)
        #expect(note.isDeleted == true)
        #expect(note.deletedDate == 1_700_000_001_000)
        #expect(note.contentFormat == "markdown")
    }
}
